### ISSUE TITLE
Modules in `mix.exs` are not found by default.

### ISSUE THREAD

**Issue by optikfluffel** [AtomLinter/linter-elixirc#10]
When I have something like this in my `mix.exs`:

```elixir
defp deps do
  [
    # ...
    { :timex, "~> 0.13.0" }
  ]
end
```

I get lint errors that the Module can't be found:

```elixir
defmodule Exq.Stats do
  use GenServer
  use Timex
  require Logger

  # ...
end
```

![screen shot 2015-07-16 at 13 50 59](https://cloud.githubusercontent.com/assets/379915/8722168/ffffc8a4-2bc1-11e5-8bf5-499f794b9c65.png)

Is there something I missed or had to configure?

Thanks :cat:

**Comment by remiq** [comment]
@optikfluffel : Please check latest version of the plugin - 1.0.0
If `mix.exs` exists in project's directory, plugin will use `mix compile`.
