### ISSUE TITLE
Is there any way to add a config file?

### ISSUE THREAD

**Issue by michaelfich** [AtomLinter/linter-elixirc#109]
I've looked around for docs on setting up a per-project linter config file for `elixirc` but I am unable to find any.  If anyone has come across such a doc, a little help would be appreciated.

**Comment by Arcanemagus** [comment]
You'll need to use something like [project-manager](https://atom.io/packages/project-manager) currently. Follow https://github.com/atom/atom/issues/5168 for any progress on getting this implemented in Atom itself.
