### ISSUE TITLE
breaks inotify-tools in phoenix app on linux

### ISSUE THREAD

**Issue by brainlid** [AtomLinter/linter-elixirc#32]
When Atom has this extension installed and active, it somehow interferes with the inotify events in Linux. This means I make a code change in a controller and phoenix can't detect the code change. So a server stop and restart is needed for each code changes to be applied.

Disabling this plugin allows phoenix hot-loading to work again. I do not have this problem with autocomplete-elixir.

**Comment by remiq** [comment]
The same issue as #19.
