### ISSUE TITLE
Implement specs

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-elixirc#39]
It looks like this linter does not currently have any specs written for it, adding it to the list being maintained [here](https://github.com/AtomLinter/Meta/issues/11) for tracking.

Specs do not need to be super detailed, as they should mainly test whether the package is properly running the linter plugin and parsing its messages. Leave testing of the linter functionality to the author of the linter.

If you need any help feel free to ask!

**Comment by joseduraes** [comment]
Hi, i will look into this.

**Comment by Arcanemagus** [comment]
If you want an example to get you started, something like [this](https://github.com/AtomLinter/linter-stylelint/tree/v2.11.0/spec) should work fine :wink:.

**Comment by Arcanemagus** [comment]
Implemented in #82.
