### ISSUE TITLE
Sometimes linter-elixirc shows error as project error even though it's in the current file

### ISSUE THREAD

**Issue by b-filip** [AtomLinter/linter-elixirc#62]
Here I have a file open.

![2016-04-15 10-58-57](https://cloud.githubusercontent.com/assets/6838251/14555105/4bdf286e-02f9-11e6-93d2-bf097ea736af.png)

The plugin shows one issue, but it's not seen at the bottom panel. If I double click at the red **issue**, this opens:

![2016-04-15 11-00-32](https://cloud.githubusercontent.com/assets/6838251/14555136/68ef056e-02f9-11e6-8bec-a46137c0bc34.png)

**Comment by Arcanemagus** [comment]
What is the output of running this in a terminal?
```ShellSession
elixirc --ignore-module-conflict --app mix --app ex_unit -o /tmp lib/el_mix/cat.ex
```

That's the simplest form of running that it does, hopefully it matches what it's really doing here.

**Comment by b-filip** [comment]
@Arcanemagus 

```
~/temp/el_mix$ elixirc --ignore-module-conflict --app mix --app ex_unit -o /tmp lib/el_mix/cat.ex
lib/el_mix/cat.ex:4: warning: variable cat is unused
```

**Comment by antipax** [comment]
@b-filip having this issue as well, looks like the problem is that a "%0A" (aka LF) is prefixing the filePath

**Comment by Arcanemagus** [comment]
@b-filip As that output doesn't contain `Compiled` it must be running it differently than that example.

To start debugging this set a breakpoint [here](https://github.com/AtomLinter/linter-elixirc/blob/v1.1.7/lib/init.coffee#L130) and post back what `resultString` contains.

If you want the _exact_ way it is running `elixirc` you'll have to follow the instructions in [this comment](https://github.com/AtomLinter/linter-elixirc/issues/63#issuecomment-214916262).

**Comment by antipax** [comment]
@Arcanemagus the issue is only happening intermittently for me, but when it does, I click on the error location, which opens a blank file, and when i click the path at the bottom of the app, it says "Copied: /path/to/app/%0Alib/my_app/module.ex".

if I can get it to happen again I will try to catch it with the debugger.

**Comment by antipax** [comment]
@Arcanemagus just got this as a path the plugin thought a file had, wasn't in dev mode at the time though:

/Users/me/Documents/Code/my_app/erl_eval.do_apply/6%0Aapps/my_app/lib/my_app/module.ex

**Comment by b-filip** [comment]
@Arcanemagus 
linter-elixirc uses [lintMix](https://github.com/AtomLinter/linter-elixirc/blob/v1.1.7/lib/init.coffee#L165), not **lintElixirc** in this project

**resultString** contains the following string:

    Compiled lib/el_mix/cat.ex
    lib/el_mix/cat.ex:4: warning: variable cat is unused

![2016-05-02 13-30-15](https://cloud.githubusercontent.com/assets/6838251/14952580/0ec1de4e-106a-11e6-8777-dc31f56b5eef.png)

**Comment by Arcanemagus** [comment]
Awesome, thanks for that!

It looks like [currently](https://regex101.com/r/nD1nH9/1) the "warning" regex is catching _both_ lines as the file name, [this fix](https://regex101.com/r/nD1nH9/2) should correct that.

**Comment by Arcanemagus** [comment]
v1.1.8 should fix this, let me know if you find anything else :wink:.
