### ISSUE TITLE
Linter is not showing compilation errors (or warnings)

### ISSUE THREAD

**Issue by chenghanlee** [AtomLinter/linter-elixirc#67]
Hi,

I just freshly installed:
 1. Atom (version 1.8.0)
 2. with linter-elixirc (version 1.1.8)
 3. on OSX (10.11.5)

Specifically, here is a screenshot of all the installed Atom packages:
![image](https://cloud.githubusercontent.com/assets/1144315/16004885/f3b851e2-3129-11e6-8fe8-6f626bb427e0.png)

and here are the linter-elixirc settings:
![image](https://cloud.githubusercontent.com/assets/1144315/16005036/ba11ece0-312a-11e6-976d-180a189e24f4.png)

I have tested my issue against both:
 1. the default settings for elixir path and mix path
 2. the absolute paths for both elixir path and mix path

For some reason,  linter-elixirc is not showing the errors or warnings that I am seeing via "mix compile" in terminal against my phoenix project.  For example, I am seeing the following compilation error in terminal:

![image](https://cloud.githubusercontent.com/assets/1144315/16004986/6a06cfea-312a-11e6-8f9c-3a6e4db9c524.png)

However, in atom, linter shows there are no issues when I save the file:

![image](https://cloud.githubusercontent.com/assets/1144315/16005021/9cf72670-312a-11e6-8497-eafe670e2b40.png)

Is this an known issue or perhaps this is an user error?

Please let me know if I can provide you with any more information to help you repro. Thank you for your help.

**Comment by Arcanemagus** [comment]
Can you open Developer Tools and put a breakpoint [here](https://github.com/AtomLinter/linter-elixirc/blob/v1.1.8/lib/init.coffee#L167) to see if it is trying to run `mix compile` as you were doing manually, and [here](https://github.com/AtomLinter/linter-elixirc/blob/v1.1.8/lib/init.coffee#L163) to see if it is running `elixirc` with some options?

If it's the second option, `elixircArgs` will contain the options it is using to execute `elixirc`.

**Comment by chenghanlee** [comment]
Thank you for your quickly reply! I really appreciate it.

I added the breakpoints in Developer Tools like you suggested, and it seems like linter-elixirc is running ```elixirc``` with some options.

And that seems to be the expected behavior as your readme mentioned:
Since ```*.ex``` files are not compiled by ```mix compile```, they are always linted using ```elixirc```.

However, it seems like linter-elixirc will not report certain compile errors when using ```elixirc``` vs ```mix compile```. Therefore, I am wondering if there are ways to force linter-elixirc to use mix compile instead of elixirc for ```*.ex``` files? 

Or perhaps that is not suggested or possible? Thanks again!

**Comment by Arcanemagus** [comment]
I'll leave that to @AtomLinter/linter-elixirc to answer as I don't actually use `elixirc` or know how project compilation works 😛.

**Comment by remiq** [comment]
@chenghanlee I've added breakpoint [here](https://github.com/AtomLinter/linter-elixirc/blob/v1.1.8/lib/init.coffee#L129) and resultString for `mix compile` is:

    /usr/bin/env: elixir: No such file or directory

resultString for `elixirc` is:

    erlexec: HOME must be set

Since those calls are internal for `mix compile` and `elixirc` I would guess that atom-linter changed it lately and linter process runs it in a different env. Do you know something about this, @Arcanemagus?

**Comment by remiq** [comment]
Everything run with atom-linter exec has following env (result of `.exec('/usr/bin/env')`:

    ELECTRON_RUN_AS_NODE=1
    ATOM_SHELL_INTERNAL_RUN_AS_NODE=1
    ELECTRON_NO_ATTACH_CONSOLE=1

Since there is no HOME, `elixirc` break. Since elixir is not on the path (for internal call of mix), `mix compile` breaks.

**Comment by remiq** [comment]
@chenghanlee Please update to 1.1.9 and check if it solved the issue.

**Comment by Arcanemagus** [comment]
@steelbrain Any idea why the environment would be blank?

**Comment by chenghanlee** [comment]
@remiq 

Thank you for your quickly reply and fixes. I've updated to linter-elixirc 1.1.9, and now linter is reporting a different error than mix compile. Seems like linter-elixirc is unable to see my phoenix project module (WebServer.Web)

Here's the linter error in Atom:
![image](https://cloud.githubusercontent.com/assets/1144315/16061609/726c3fe2-3253-11e6-926d-3e23656eb3e0.png)

Here's the mix compile error in terminal:
![image](https://cloud.githubusercontent.com/assets/1144315/16061540/1b7b694c-3253-11e6-8da4-67b57323749a.png)

Here's my linter-elixirc settings:
![image](https://cloud.githubusercontent.com/assets/1144315/16061565/30cda382-3253-11e6-8ce7-cd1e1d5f303b.png)

**Comment by remiq** [comment]
@chenghanlee Check what is the value of resultString here: https://github.com/AtomLinter/linter-elixirc/blob/v1.1.8/lib/init.coffee#L129

**Comment by steelbrain** [comment]
@Arcanemagus in the worst case scenario, consistent-env falls back to `process.env`. I have no idea why an empty env will be given

**Comment by chenghanlee** [comment]
@remiq 

Thank you for looking into this some more. 

The value of the resultString is:
```resultString = "== Compilation error on file web/views/form_view.ex ==↵** (RuntimeError) could not load template_engines configuration for Phoenix. Please ensure you have listed :phoenix under :applications in your mix.exs file and have enabled the :phoenix compiler under :compilers, for example: [:phoenix] ++ Mix.compilers↵    lib/phoenix/template.ex:238: Phoenix.Template.raw_config/1↵    lib/phoenix/template.ex:228: Phoenix.Template.compiled_engines/0↵    lib/phoenix/template.ex:300: Phoenix.Template.find_all/1↵    expanding macro: Phoenix.Template.__before_compile__/1↵    web/views/form_view.ex:1: WebServer.FormView (module)↵"
130
        errorStack = parseError(resultString, textEditor)
```

And my mix.exs is as follows:

```defmodule WebServer.Mixfile do
  @moduledoc false
  
  use Mix.Project

  def project do
    [app: :web_server,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {WebServer, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :comeonin, :timex_ecto]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.1.4"},
     {:phoenix_ecto, "~> 3.0.0-rc"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.5.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:comeonin, "~> 2.3"},
     {:slugger, "~> 0.1.0"},
     {:guardian, "~> 0.10.0"},
     {:timex, "~> 2.1.6"},
     {:timex_ecto, "~> 1.1.1"},
     {:credo, "~> 0.4", only: [:dev, :test]}]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.migrate", "test"]]
  end
end
```

From the error in resultString, it seems like linter-elixirc is having troubles playing nicely with phoenix?

**Comment by remiq** [comment]
@chenghanlee `resultString` looks parsable (except there is no line number). Are you sure that `mix compile` in the console result is different than one in resultString? I don't have any problem with phoenix and linter-elixir.

**Comment by chenghanlee** [comment]
@remiq 

This is what I see in my terminal via 
```
CHENG-HANs-MacBook-Pro:web_server chenghan$ mix compile

== Compilation error on file web/views/form_view.ex ==
** (CompileError) web/views/form_view.ex:5: undefined function this_is_an_error/0
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

And the linter error that I see above makes me think that my linter-elixirc install is not seeing my mix.exs. Specfically this part.
`
(RuntimeError) could not load template_engines configuration for Phoenix. Please ensure you have listed :phoenix under :applications in your mix.exs file and have enabled the :phoenix compiler under :compilers, for example: [:phoenix] ++ Mix.compilers↵  ` 

Perhaps this is an user error specific to my setup. 

Anyways, thank you for your help and diagnosis!

**Comment by remiq** [comment]
@chenghanlee I have no ideas why mix would not find mix.exs. You can check opts, maybe cwd is null? https://github.com/AtomLinter/linter-elixirc/blob/v1.1.8/lib/init.coffee#L139

**Comment by chenghanlee** [comment]
@remiq: Apologies for the late reply. It is strange ... cwd shows the fullpath to my mix.exs. 

Seems like no one else is suffering the same issues as I am. I am going to close this issue as non-repro and see if I can do more debugging on my own. Thank you for your help throughout the process.
