### ISSUE TITLE
Getting compilation lint warnings, but no style warnings?

### ISSUE THREAD

**Issue by sergiotapia** [AtomLinter/linter-elixirc#70]
This flags bad code, which works great.

<img width="456" alt="screen shot 2016-06-29 at 10 43 25 am" src="https://cloud.githubusercontent.com/assets/686715/16456616/826f8b76-3de6-11e6-9857-36fe143f4503.png">

This ugly code isn't flagged though - unless this is actually good Elixir? (I'm new to Elixir)

<img width="276" alt="screen shot 2016-06-29 at 10 43 46 am" src="https://cloud.githubusercontent.com/assets/686715/16456623/87c3ca56-3de6-11e6-98b8-957a410be210.png">

Are there supposed to be flags on that second screenshot? I'm looking for something like Rubocop for Elixir.

**Comment by Arcanemagus** [comment]
As this is actually just compiling your code and showing the compilation errors in Atom, there is no style checking going on.

I don't think there _is_ a style linter for Elixir yet, but as I don't actually use the language I'm not the person to ask 😛.

**Comment by remiq** [comment]
Linter checks for compilation error/warning.
There is no "one correct way to write Elixir", but there is https://github.com/rrrene/credo

**Comment by sergiotapia** [comment]
I gotcha, I was under the impression this was like Rubocop for Elixir.
