### ISSUE TITLE
Line number greater than maximum line

### ISSUE THREAD

**Issue by miskolc** [AtomLinter/linter-elixirc#76]
`priv/repo/seeds.exs`

```
alias AppName.Repo
alias AppName.Shop
AppName.insert!(%Shop{}) # this is line 14
```

`$ elixirc --ignore-module-conflict --app mix --app ex_unit -o /tmp priv/repo/seeds.exs `

```
== Compilation error on file priv/repo/seeds.exs ==
** (CompileError) priv/repo/seeds.exs:14: AppName.Shop.__struct__/1 is undefined, cannot expand struct AppName.Shop
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

CTRL + S Atom error:

```
Error: Line number (415) greater than maximum line (14)
Error: Line number (415) greater than maximum line (14)
    at Object.rangeFromLineNumber (/home/miskolc/.atom/packages/linter-elixirc/node_modules/atom-linter/lib/index.js:178:11)
    at parseError (/home/miskolc/.atom/packages/linter-elixirc/lib/init.coffee:99:28)
    at /home/miskolc/.atom/packages/linter-elixirc/lib/init.coffee:130:22
```

**Comment by miskolc** [comment]
Running the `seed.exs` file seems to work, but the linter still shows the error and It's annoying to have it on while you are editing the seeds file because every same with pop a large red rectangle in atom.

I suspect the linter can't see the `AppName` modules so it thinks there's an error. Maybe this behaviour can be fixed, or if not then the linter should ignore saves on the seed files.

**Comment by JustinAiken** [comment]
I'm having the same issue with `test/test_helper.exs`, if I have just this line in it:

```elixir
Ecto.Adapters.SQL.Sandbox.mode(UserTesting.Repo, :manual)
```

The `UserTesting.Repo` is from `lib/usertesting/repo.ex`

**Comment by remiq** [comment]
@miskolc @JustinAiken Version 1.1.11 suppresses this error message.
