### ISSUE TITLE
Some user defined modules are not found if includeDirs is not defined

### ISSUE THREAD

**Issue by tobarja** [AtomLinter/linter-elixirc#9]
After setting up my first phoenix project, I noticed that MyProject.Web was flagged with a module not found message. I played with the settings a little while and discovered that setting any value in this field makes the error go away.

**Comment by remiq** [comment]
@tobarja : Please check latest version of the plugin - 1.0.0
If `mix.exs` exists in project's directory, plugin will use `mix compile`.
