### ISSUE TITLE
Not finding modules in test directory

### ISSUE THREAD

**Issue by davelively14** [AtomLinter/linter-elixirc#90]
I have the module `MyApp.DataCase` defined at `test/support/data_case.ex`, yet I keep getting this error from the linter:

`(CompileError) module MyApp.DataCase is not loaded and could not be found	2:3
test/spade_inspector/otp/server_test.exs1002:3
LFUTF-8Elixirimplement-parsing+4git+2 updates`

I get this error in all of my test files, but I get no errors when compiled and all my tests pass. Any ideas?

**Comment by mauricerkelly** [comment]
Hi @davelively14. That certainly sounds unusual and must be very frustrating!

Could I trouble you to do a few things for me?

* Can you let me know what settings you are using: are you using a specific Mix environment for linting, or do you have `Always use elixirc` enabled?
* Can you check to see if your module `MyApp.DataCase` is visible in the following folder: `_build/test/lib/myapp/ebin` (where `myapp` is the name of your app - could be `my_app` maybe). The filename should be something like `Elixir.MyApp.ConnCase.beam`
* If you are able to, can you re-create just this issue in a standalone project that I can use for debugging?

Cheers,

Maurice

**Comment by davelively14** [comment]
Thanks @mauricerkelly. 

- My settings are all default (elixirc, mix env, and mix path) and I do not have `Always use elixirc` enabled.
- Yes, `_build/test/lib/flatfoot/ebin/Elixir.MyApp.DataCase.beam` exists.
- [Here's a standalone project](https://github.com/davelively14/test_debug_linter) I just threw together. I get the same error in `test/web/controllers/page_controller_test.exs`.

Thanks much, and no worries about frustration! It works great where I really need it (all my non-test code) - I appreciate you putting this together.

**Comment by mauricerkelly** [comment]
Thanks for the quick response and the test project - it may take me a few days to get looking at it, but it's firmly on my radar.

The project isn't my doing really -- I've just waded in lately and started helping out 😀

**Comment by mauricerkelly** [comment]
Hi @davelively14, this issue should be fixed, but is pending release. I'll update you here when it has been released. Thanks for supplying the sample project - it was most helpful in debugging the issue!

**Comment by davelively14** [comment]
Thanks, Maurice!

**Comment by mauricerkelly** [comment]
Hi @davelively14 - there's a new release (v1.6.0) of the plugin available which includes a couple of fixes, including the fix for this issue. I'm going to close this issue now, but if you feel that it isn't resolved we can open a new one. Thanks again for your help.
